---
kind: pkgfile.Build
spec:
  targets:
    - talos-sbc-mixtile-blade3
  extraBuildArgs:
    - PKGS_PREFIX
    - PKGS
  makefile:
    extraVariables:
      - name: PKGS_PREFIX
        defaultValue: ghcr.io/siderolabs
      - name: PKGS
        defaultValue: v1.7.0
---
kind: common.Build
spec:
    ignoredPaths:
      - go.work.sum
